name: 'Send message to google chat'
description: 'Sends a message about the availability of a new build to the chat.'
author: '[Inmost]'

inputs:
  WEBHOOK_URL:
    description: 'Google Chat Webhook'
    required: true
  HEAD_COMMIT:
    description: 'Git Commit Info'
    required: true
  APPLICATION_TYPE:
    description: 'Can be [MOBILE, SERVER, WEB]'
    required: true
  BRANCH_REF:
    description: 'Branch ref'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
